server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Enable discovery client integration
          lower-case-service-id: true
      routes:
        - id: book-service
          uri: lb://book-service
          predicates:
            - Path=/api/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: book-service
                fallbackUri: forward:/fallback/book-service

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: user-service
                fallbackUri: forward:/fallback/user-service

        - id: borrowing-service
          uri: lb://borrowing-service
          predicates:
            - Path=/api/borrowings/**
          filters:
            - name: CircuitBreaker
              args:
                name: borrowing-service
                fallbackUri: forward:/fallback/borrowing-service

        # Discovery Service (Eureka Dashboard)
        - id: discovery-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web/**
          filters:
            - RewritePath=/eureka/web/(?<segment>.*), /$\{segment}

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# Actuator Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway
  endpoint:
    health:
      show-details: always
