server:
  port: 8083

spring:
  application:
    name: borrowing-service
  r2dbc:
    url: r2dbc:h2:mem:///borrowingdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  webflux:
    base-path: /api
  codec:
    max-in-memory-size: 10MB

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# External Services URLs (will be discovered via Eureka)
service:
  book-service: http://book-service
  user-service: http://user-service

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
