server:
  port: 8083

spring:
  application:
    name: borrowing-service
  datasource:
    url: jdbc:h2:mem:borrowingdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

# External Services URLs (will be discovered via Eureka)
service:
  book-service: http://book-service
  user-service: http://user-service

logging:
  level:
    org.springframework: INFO
    com.example: DEBUG
